# Generated by Django 4.2.7 on 2026-01-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('COD', 'COD')], default='ONLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('PAID', 'PAID'), ('COD_CONFIRMED', 'COD_CONFIRMED'), ('FAILED', 'FAILED')], default='CREATED', max_length=20),
        ),
    ]
