# Generated by Django 5.0.1 on 2026-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_delivery_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(db_index=True, default='Mumbai', max_length=100),
        ),
    ]
