# Generated by Django 5.2.5 on 2026-01-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_product_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('uploading', 'Uploading'), ('delivered', 'Delivered'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
