# Generated by Django 5.2.5 on 2025-11-28 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('business_name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('subcategory_ids', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=64, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='vendor_app__user_id_af782d_idx'), models.Index(fields=['status'], name='vendor_app__status_d8dd8f_idx')],
            },
        ),
    ]
