# Generated by Django 5.2.9 on 2026-01-06 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_scheduletask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('away', 'Away')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
