# Generated by Django 5.2.10 on 2026-01-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_vendorprofile_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='vendor_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
