# Generated by Django 5.2.9 on 2026-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user_id', 'vendor_id'], name='chat_app_ch_user_id_19db58_idx'),
        ),
    ]
