# Generated by Django 5.2.9 on 2026-01-02 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_chatmessage_chat_app_ch_user_id_19db58_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
            preserve_default=False,
        ),
    ]
