# Generated by Django 5.2.9 on 2026-01-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_populate_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['vendor_id', 'is_read'], name='chat_app_ch_vendor__6b0258_idx'),
        ),
    ]
