# Generated by Django 5.2.9 on 2026-01-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=10),
        ),
    ]
