# Generated by Django 5.2.5 on 2026-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING_APPROVAL', 'AWAITING_APPROVAL'), ('PARTIALLY_APPROVED', 'PARTIALLY_APPROVED'), ('PAID', 'PAID'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='vendor_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
