# Generated by Django 4.2.7 on 2026-01-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_masterorder_status_alter_suborder_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING_APPROVAL', 'AWAITING_APPROVAL'), ('PARTIALLY_APPROVED', 'PARTIALLY_APPROVED'), ('FULLY_APPROVED', 'FULLY_APPROVED'), ('PAID', 'PAID'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
