# Generated by Django 4.2.7 on 2026-01-11 09:26

import bookings.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField()),
                ('vendor_id', models.UUIDField()),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('HOLD', 'HOLD'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='HOLD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=bookings.models.default_expiry)),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('vendor_id', 'event_date'), name='unique_vendor_event_date'),
        ),
    ]
