# Generated by Django 5.2.5 on 2026-01-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_idempotencykey'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_vendor_event_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['HOLD', 'CONFIRMED'])), fields=('vendor_id', 'event_date'), name='unique_active_booking'),
        ),
    ]
