# Generated by Django 5.2.5 on 2026-01-12 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_unique_vendor_event_date_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='orders.suborder'),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('key', 'user_id'), name='unique_idempotency_per_user'),
        ),
    ]
