# Generated by Django 5.2.5 on 2026-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_order_id_booking_sub_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('HOLD', 'HOLD'), ('AWAITING_APPROVAL', 'AWAITING_APPROVAL'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], default='AWAITING_APPROVAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vendor_id',
            field=models.CharField(max_length=100),
        ),
    ]
