# Generated by Django 4.2.7 on 2026-01-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status_alter_booking_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category_name',
            field=models.CharField(default='Service', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(default='Event', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='product_name',
            field=models.CharField(default='Event Service', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='vendor_name',
            field=models.CharField(default='Aivent Partner', max_length=255),
        ),
    ]
